### PR TITLE
Remove event-stream and some deps

### PR DESCRIPTION
**Pull request by CAYdenberg**
@MarkBennett @snostorm any objections?

### CODE REVIEW

**Comment by nathany** [comment]
Apologies for the delay. It looks like we may need a few more updates.

```
❯ npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
# Run  npm install --save-dev webpack-dev-server@3.1.14  to resolve 1 vulnerability
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Missing Origin Validation                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ webpack-dev-server                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ webpack-dev-server [dev]                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ webpack-dev-server                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/725                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


# Run  npm update embedly --depth 2  to resolve 3 vulnerabilities
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ mime                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ keystone                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ keystone > embedly > superagent > mime                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/535                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ keystone                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ keystone > embedly > lodash                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/577                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Large gzip Denial of Service                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ superagent                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ keystone                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ keystone > embedly > superagent                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/479                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ keystone                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ keystone > less-middleware > less > request > hawk > boom >  │
│               │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ keystone                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ keystone > less-middleware > less > request > hawk >         │
│               │ cryptiles > boom > hoek                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ keystone                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ keystone > less-middleware > less > request > hawk > hoek    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ keystone                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ keystone > less-middleware > less > request > hawk > sntp >  │
│               │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.5                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ keystone                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ keystone > asyncdi > lodash                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/577                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.5                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ keystone                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ keystone > grappling-hook > lodash                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/577                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.5                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ keystone                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ keystone > expression-match > lodash                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/577                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 11 vulnerabilities (5 low, 5 moderate, 1 high) in 10969 scanned packages
  run `npm audit fix` to fix 4 of them.
  7 vulnerabilities require manual review. See the full report for details.
```

**Comment by CAYdenberg** [comment]
Morgan: prints out a console message whenever a request to the server. Useful in development to see what's happening/what routes are being hit.

npm task: pretty much redundant with just typing "gulp watch" but maybe it's useful so that you don't need gulp installed.

I'll take a look at that audit -- I was doing this in a hurry to get rid of event-stream but the crisis seems to have passed.

**Comment by CAYdenberg** [comment]
OK, I killed two birds with one stone and got rid of gulp completely. You can now (still) do `npm run dev` and it will spin up a server (with nodemon) and the webpack dev server, proxying the main server.

We still have to build before pushing so that Heroku has compiled JS files to work with - I imagine Travis should be able to do that for us?

The other things picked up by `npm audit` are all underneath Keystone (4.0.0) which is not being maintained per se right now. So that will be a problem at some point -- right now nothing is high/severe however.

**Comment by CAYdenberg** [comment]
I think the Travis build needs to be updated. Seems to be failing at
```
http://dl.bintray.com/apache/cassandra/dists/39x/main/binary-amd64/Packages
```

**Comment by MarkBennett** [comment]
@CAYdenberg it looks like everything is passing now. Is this ready for merging?

**Comment by CAYdenberg** [comment]
Under 3 months to patch an NPM package :party: :balloon: :rocket:

**Pull request merged**
