### PR TITLE
Easy pacakge updates

### PR DESCRIPTION
**Pull request by MarkBennett**
This is some of the low-hanging packages which are easy upgrades on the site.

There's lots that's outdated though so the work isn't done...

```
10:37 ~/projects/exchangejs/exchangejs.com (security-updates)
$ yarn outdated
yarn outdated v1.6.0
(node:53740) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info Color legend :
 "<red>"    : Major Update backward-incompatible updates
 "<yellow>" : Minor Update backward-compatible features
 "<green>"  : Patch Update backward-compatible bug fixes
Package            Current      Wanted  Latest Package Type    URL
babel-loader       6.4.1        6.4.1   7.1.5  devDependencies https://github.com/babel/babel-loader
body-parser        1.8.4        1.8.4   1.18.3 dependencies    https://github.com/expressjs/body-parser#readme
connect-mongo      1.3.2        1.3.2   2.0.1  dependencies    https://github.com/jdesboeufs/connect-mongo#readme
cookie-parser      1.3.5        1.3.5   1.4.3  dependencies    https://github.com/expressjs/cookie-parser
debug              2.0.0        2.0.0   3.1.0  dependencies    https://github.com/visionmedia/debug#readme
dotenv             4.0.0        4.0.0   6.0.0  dependencies    https://github.com/motdotla/dotenv#readme
express            4.9.8        4.9.8   4.16.3 dependencies    http://expressjs.com/
keystone           4.0.0-beta.5 4.0.0   4.0.0  dependencies    http://keystonejs.com/
mongoose           4.8.4        4.13.15 5.2.9  dependencies    http://mongoosejs.com
morgan             1.3.2        1.3.2   1.9.0  dependencies    https://github.com/expressjs/morgan#readme
serve-favicon      2.1.7        2.1.7   2.5.0  dependencies    https://github.com/expressjs/serve-favicon#readme
webpack            1.15.0       1.15.0  4.17.1 devDependencies https://github.com/webpack/webpack
webpack-dev-server 1.16.5       1.16.5  3.1.5  devDependencies https://github.com/webpack/webpack-dev-server
✨  Done in 0.80s.
```

### CODE REVIEW

**Comment by MarkBennett** [comment]
Mind taking a look at this when you have a minute @CAYdenberg? I'll try to update `keystone`, `mongoose` and `webpack` at a later date.

**Comment by CAYdenberg** [comment]
I don't work with yarn much but the only updated file is `yarn.lock`. Shouldn't you update `package.json` too?

**Comment by MarkBennett** [comment]
Hmm @CAYdenberg . I've been using `yarn` when I work as per the `README`. Perhaps we should pick one to use rather than try to maintain both?

I feel like `yarn` is faster and it's what I use on most of my React projects so that would get my vote, but I've heard `npm` has improved. It's got a lock file now too but I can't say I know how to use it.

**Comment by CAYdenberg** [comment]
I'm happy to stick with yarn, but I think it should still be updating package.json. 

I checked out your branch, ran `yarn install` and then `yarn outdated` and saw all the same results as above. I tried running `yarn add --dev babel-loader` and babel-loader disappeared from the outdated packages, but *both* yarn.lock and package.json were modified.

So I'm pretty sure yarn still works with package.json, and if changes aren't made/committed there they can't be reproduced in a clone of the repo.

**Comment by MarkBennett** [comment]
> I'm happy to stick with yarn, but I think it should still be updating package.json.
> 
> I checked out your branch, ran yarn install and then yarn outdated and saw all the same results as above. I tried running yarn add --dev babel-loader and babel-loader disappeared from the outdated packages, but both yarn.lock and package.json were modified.
> 
> So I'm pretty sure yarn still works with package.json, and if changes aren't made/committed there they can't be reproduced in a clone of the repo.

Ok. That makes sense @CAYdenberg 

I think that probably make sense as the `yarn upgrade <XYZ>` commands I used won't change the `package.json` just the lock. Updating what's in `package.json` and the outdated major versions will be a separate PR.

**Comment by CAYdenberg** [comment]
I think you can just use `yarn add` and the package you want to update.

**Comment by MarkBennett** [comment]
> I think you can just use yarn add and the package you want to update.

That sounds right. Some of the upgrades are bigger though and will need changes to the source and config (`webpack` and `keystone`) in particular, so I'll do those in a separate PR.

**Pull request closed without merging**
